#!python3

from dataclasses import dataclass
from multiprocessing import cpu_count
from typing import  Union


from .boards import Boards
from .calibrate import Calibrate
from .intrinsic import Intrinsic
from .vis import Vis


@dataclass
class Program:
  """ multical - multi camera calibration """ 
  command : Union[Calibrate, Intrinsic, Boards, Vis]
   
  def execute(self):
    return self.command.execute()
