#!python

from multical.app import arguments

from multical.app.calibrate import calibrate
from multical.app.boards import show_boards
from multical.app.vis import visualize
from multical.app.intrinsic import calibrate_intrinsic


def main():
  parser = arguments.parser()
  args = parser.parse_args()

  if 'which' not in args:
    parser.print_help()
  elif args.which == "calibrate":
    calibrate(args)
  elif args.which == "intrinsic":
    calibrate_intrinsic(args)
  elif args.which == "vis":
    visualize(args)
  elif args.which == "boards":
    show_boards(args)
  else:
    assert False, f"unknown command {args.which}"



if __name__ == "__main__":
  main()